"""empty message

Revision ID: 271421deb917
Revises: e781a64fdb74
Create Date: 2025-05-01 11:07:50.305800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271421deb917'
down_revision = 'e781a64fdb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
